### PR TITLE
fix label for ecrro_0000137

### PR DESCRIPTION
**Pull request by smrgeoinfo**
change places to applications

### CODE REVIEW

**Review by rduerr — CHANGES_REQUESTED** [review]
Actually thinking about it more - I actually think that this should not get fixed.  I can imagine that for non-code resources the term "places" would make more sense than the term "applications"

**Comment by rduerr** [comment]
I will go update our spreadsheet accordingly if you agree....

**Comment by smrgeoinfo** [comment]
I think the spreadsheet was already the correct term, it just got shifted in the owl file

**Comment by rduerr** [comment]
No actually not, it needs to be places since applications is not relevant to many of the non-software type of resources whereas to the best of my knowledge "places" works for all types of resources...

**Comment by smrgeoinfo** [comment]
Close without merging, don't make change

**Pull request closed without merging**
