### PR TITLE
create examples folder and add sweet schema.org example

### PR DESCRIPTION
**Pull request by smrgeoinfo**

### CODE REVIEW

**Comment by rduerr** [comment]
So lots of comments...  

1. So why does this example have sooo.... many @types?  It is a set of ontologies so should be noted as such.  Yes, schema.org doesn't include such a tag; but that is a valid EC resource type according to your google doc and that definitely needs to be included here.  I would consider that an extension point.

2. Strangely enough I object to SWEET being considered either a Dataset or a Product and am surprised that either VIVO or geolink would include SWEET as a dataset.  It certainly isn't a dataset in the sense that your average geoscientist would be looking for.

3. I doubt if ESIP would like the citation you gave it, especially not for the current version (that citation works for version 1 though).  

4. "status": "Used in multiple places" should read "Used in multiple applications" per Resource Descriptions 2019-03 document.

5. I take it you decided that it wasn't necessary to distinguish usage by technologists from usage by geoscientists?  In this case, it is easy to say that technologists would be the only ones directly using it (to develop tools, etc.), in which case the phrases from the Resource Descriptions document should be used.

6. What is this identifier you used "http://earthcube.org/resources/35736487"?  I thought we were going to use UUID's?  ARKs?

7. Rob and friends might have created SWEET, but the number of people who should be getting credit is way more than just Rob at this point.  I suggest this record just be for the version that corresponds to the paper cited several times herein.  Otherwise the number of fields that need updating is large (e.g., date published), though the version would need to be downgraded to pre-ESIP days.

8. The main distribution for sweet is likely to be http://cor.esipfed.org/ont/api/v0/ont?format=rj&iri=http://sweetontology.net/sweetAll which is a URL that directly loads into Protege!!!

9. The Resource Registry is not now nor never will be a DataCatalog in the DCAT sense of that term!!!  This is a place where extending schema.org is absolutely needed.

10. SWEET is not a vocabulary!  It is an ontology!!!  Another important extension point (though I thought that was in schema.org)

11. Spatial coverage is not really relevant to SWEET.  It is not a dataset in the sense that geoscientists would be looking for, so neither spatial or temporal coverage are relevant.

12. Where did this set of keywords come from?

**Review by rduerr — COMMENTED** [review]
So lots of comments...

1.    So why does this example have sooo.... many @types? It is a set of ontologies so should be noted as such. Yes, schema.org doesn't include such a tag; but that is a valid EC resource type according to your google doc and that definitely needs to be included here. I would consider that an extension point.

2.    Strangely enough I object to SWEET being considered either a Dataset or a Product and am surprised that either VIVO or geolink would include SWEET as a dataset. It certainly isn't a dataset in the sense that your average geoscientist would be looking for.

3.    I doubt if ESIP would like the citation you gave it, especially not for the current version (that citation works for version 1 though).

4.    "status": "Used in multiple places" should read "Used in multiple applications" per Resource Descriptions 2019-03 document.

5.    I take it you decided that it wasn't necessary to distinguish usage by technologists from usage by geoscientists? In this case, it is easy to say that technologists would be the only ones directly using it (to develop tools, etc.), in which case the phrases from the Resource Descriptions document should be used.

6.    What is this identifier you used "http://earthcube.org/resources/35736487"? I thought we were going to use UUID's? ARKs?

7.    Rob and friends might have created SWEET, but the number of people who should be getting credit is way more than just Rob at this point. I suggest this record just be for the version that corresponds to the paper cited several times herein. Otherwise the number of fields that need updating is large (e.g., date published), though the version would need to be downgraded to pre-ESIP days.

8.    The main distribution for sweet is likely to be http://cor.esipfed.org/ont/api/v0/ont?format=rj&iri=http://sweetontology.net/sweetAll which is a URL that directly loads into Protege!!!

9.    The Resource Registry is not now nor never will be a DataCatalog in the DCAT sense of that term!!! This is a place where extending schema.org is absolutely needed.

10.    SWEET is not a vocabulary! It is an ontology!!! Another important extension point (though I thought that was in schema.org)

11.    Spatial coverage is not really relevant to SWEET. It is not a dataset in the sense that geoscientists would be looking for, so neither spatial or temporal coverage are relevant.

12.    Where did this set of keywords come from?

**Comment by smrgeoinfo** [comment]
Responses to Ruth's questions in separate comments
1. So why does this example have sooo.... many @types? It is a set of ontologies so should be noted as such. Yes, schema.org doesn't include such a tag; but that is a valid EC resource type according to your google doc and that definitely needs to be included here. I would consider that an extension point.

The @Type declarations are necessary to declare the type of an element value when it is another sdo class.   I don't understand the rest of the comment.

**Comment by smrgeoinfo** [comment]
2 Strangely enough I object to SWEET being considered either a Dataset or a Product and am surprised that either VIVO or geolink would include SWEET as a dataset. It certainly isn't a dataset in the sense that your average geoscientist would be looking for.

I"d have to agree, I'd call it an information model or DefinedTermSet

**Comment by smrgeoinfo** [comment]
Ruth just merged the branch..   Most of the other comments are specific to the content in the example that I mostly made up ad hoc just to get some content in the elements.  WE'll need a better record for SWEET in the real registry.

**Comment by rduerr** [comment]
I merged it because after our discussion I had agreed that while not a great example, it was good enough for a starting point and having examples is good.  I think your comment above should be a new issue (i.e., need a better record for SWEET in the real registry).

**Pull request merged**
